### ISSUE TITLE
If nothing is piped, process just hangs. (On Windows)

### ISSUE THREAD

**Issue by st0le** [todoesverso/logss#6]
If nothing is piped, process just hangs. Doesn't respond to esc/ctrl+c to close.

Tried on windows only.

**Comment by todoesverso** [comment]
It should be fixed in

https://github.com/todoesverso/logss/releases/tag/v1.1.0-alpha

**Comment by todoesverso** [comment]
This should be done so I'll close it. Feel  free to re open it.
